server:
  port: 8081

security:
  jwt:
    secret-base64: ${JWT_SECRET_BASE64}
    issuer: bank-bootcamp
    audience: bank-api

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: client_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true