server:
  port: 8084

security:
  jwt:
    secret-base64: ${JWT_SECRET_BASE64}
    issuer: bank-bootcamp
    audience: bank-api

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: transaction_db
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-ledger
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.banco.transactionservice.event
        spring.json.value.default.type: com.banco.transactionservice.event.YankiPaymentCompletedEvent
        spring.json.use.type.headers: false

yanki:
  kafka:
    payment-completed-topic: yanki.payment.completed.v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true